# Generated by Django 3.0.8 on 2021-06-12 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.ManyToManyField(related_name='s_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
