# Generated by Django 3.0.8 on 2021-06-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
